language: python

sudo: required
os: linux
dist: trusty
group: edge

services:
    - docker
python:
    - "3.6"

env:
    matrix:
        - TESTENV=docs
        - TESTENV=code
        - TESTENV=pylint
        - TESTENV=build

before_install:
  - wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/bigWigToWig
  - chmod +x ./bigWigToWig
  - chmod +x ./travis/docs_harness.sh
  - chmod +x ./travis/pylint_harness.sh
# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install --upgrade setuptools
    - if [[ "$TESTENV" == "docs" ]]; then pip install sphinx;fi
    - if [[ "$TESTENV" == "pylint" ]]; then pip install pylint;fi
    - if [[ "$TESTENV" == "build" ]]; then pip install pyinstaller;fi

# command to run tests
script:
    - if [[ "$TESTENV" == "code" ]]; then pytest tests; fi
    - if [[ "$TESTENV" == "docs" ]]; then ./travis/docs_harness.sh; fi
    - if [[ "$TESTENV" == "pylint" ]]; then ./travis/pylint_harness.sh; fi
    - if [[ "$TESTENV" == "build" ]]; then pyinstaller --onefile ./GC_analysis/GC_analysis.py; docker build -t tonyyzy/gc_analysis .; fi

before_deploy:
    - sed -i -e 's/TAG_VERSION/'$TRAVIS_TAG'/g' setup.py
    - echo $TRAVIS_TAG
    - cat setup.py
deploy:
  - provider: releases
    skip-cleanup: true
    file: ./dist/GC_analysis
    api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      tags: true
      condition: $TESTENV = "build"

  - provider: script
    script: bash ./travis/docker_push.sh
    on:
      tags: true
      condition: $TESTENV = "build"

  - provider: pypi
    skip-cleanup: true
    user: tonyyzy
    password: $PYPI_PASSWORD
    distributions: sdist bdist_wheel
    on:
      tags: true
      condition: $TESTENV = "build"
       
